# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db-debug:
    image: mariadb
    container_name: db-debug
    environment: 
      MYSQL_DATABASE: "ItemPriceWatcher"
      MYSQL_ROOT_PASSWORD: "d3bugP@ssw0rd"
      MYSQL_USER: pricewatcherdebug
      MYSQL_PASSWORD: debugpass
    ports:
      - "6033:3306"
    volumes:
      - ./Deploy/conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  itempricewatchermanager:
    image: itempricewatchermanager
    build:
      context: .
      dockerfile: ItemPriceWatcher.Manager/Dockerfile
    depends_on: 
      db-debug:
        condition: service_started
    environment: 
      CONN_STRING: "Server=db-debug; Database=ItemPriceWatcher; Port=3306; Uid=root; Pwd=d3bugP@ssw0rd"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    ports: 
    - "5001:5001"
    - "5080:80"