# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  itempricewatchermanager:
    image: itempricewatchermanager
    build:
      context: .
      dockerfile: ItemPriceWatcher.Manager/Dockerfile
    ports:
      - 80
