USE ItemPriceWatcher;

CREATE TABLE WatchItem (
    WatchItemID INT AUTO_INCREMENT PRIMARY KEY,
    WatchItemName VARCHAR(30) NOT NULL,
    WebsiteUrl VARCHAR(200) NOT NULL,
    ItemPath VARCHAR(200) NOT NULL
);